# Generated by Django 5.0.3 on 2024-03-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(choices=[('ISC', 'Ingeniería en Sistemas Computacionales'), ('CP', 'Contador Público'), ('IGE', 'Ingeniería en Gestión Empresarial')], default='ISC', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposFormatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formato', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formato', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField()),
                ('tipo_formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tiposformatos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Personal', 'Personal')], max_length=50)),
                ('numero_control', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('servicio', models.BooleanField()),
                ('residencia', models.BooleanField()),
                ('ingles', models.BooleanField()),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('dependencia_organizacion', models.CharField(max_length=255)),
                ('titular_organizacion', models.CharField(max_length=255)),
                ('cargo_titular', models.CharField(max_length=255)),
                ('atencion_a_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('atencion_a_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
