# Generated by Django 5.0.3 on 2024-03-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciosocial',
            options={'verbose_name_plural': 'Servicio Social'},
        ),
        migrations.AlterModelOptions(
            name='tiposformatos',
            options={'verbose_name_plural': 'Tipos de Formatos'},
        ),
        migrations.RemoveField(
            model_name='formato',
            name='ruta_archivo',
        ),
        migrations.AddField(
            model_name='formato',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='formatos/'),
        ),
    ]
