# Generated by Django 5.0.3 on 2024-03-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usuario_email_alter_usuario_numero_control'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='numero_control',
            new_name='username',
        ),
    ]
